import type { Metadata } from "next";
import SideBar from "@/app/(dentist)/components/SideBar";
import SmallScreenSideBar from "../components/SmallScreenSideBar";

export const metadata: Metadata = {
  title: "Aspire Consent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      {/* Desktop Sidebar */}
      <div className="hidden lg:flex lg:w-[19%] z-30">
        <SideBar />
      </div>

      {/* Mobile Sidebar Wrapper */}
      <div className="lg:hidden relative z-40">
        <SmallScreenSideBar />
      </div>

      {/* Main Content */}
      <main className="flex-1 bg-white p-6 pt-0 lg:pt-6 z-0 relative">
        {children}
      </main>
    </div>
  );
}
