import type { Metadata } from "next";
import { DashboardIcon } from "@/asssets";
import SideBarWrapper from "@/components/SideBarWrapper";
import SmallScreenSideBarWrapper from "@/components/SmallScreenSideBarWrapper";

export const metadata: Metadata = {
  title: "Aspire Consent",
  description: "Generated by create next app",
};
const SIDE_BAR_DATA = [
  { text: "Dashboard", logo: DashboardIcon, link: "/patient/dashboard" },
  // {
  //   text: "Consent Forms",
  //   logo: ConsentFormIcon,
  //   link: "/patient/consent-forms",
  // },
  // { text: "Patients", logo: PatientIcon, link: "/patient/patients" },
  // { text: "Settings", logo: SettingIcon, link: "/settings" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      {/* Desktop Sidebar */}
      <div className="hidden lg:block fixed lg:w-[19%] 2xl:w-[15%] h-screen z-30">
        {/* <SideBar data={SIDE_BAR_DATA} /> */}
        <SideBarWrapper data={SIDE_BAR_DATA} />
      </div>

      {/* Mobile Sidebar Wrapper */}
      <div className="lg:hidden relative z-40">
        <SmallScreenSideBarWrapper data={SIDE_BAR_DATA} />
      </div>
      {/* Main Content */}
      <main className="flex-1 bg-white p-6 pt-0 lg:pt-6 z-0 relative">
        {children}
      </main>
    </div>
  );
}
