import type { Metadata } from "next";
import SideBar from "@/components/SideBar";
import SmallScreenSideBar from "@/components/SmallScreenSideBar";
import { ConsentFormIcon, DashboardIcon } from "@/asssets";

export const metadata: Metadata = {
  title: "Aspire Consent",
  description: "Generated by create next app",
};

const SIDE_BAR_DATA = [
  { text: "Dashboard", logo: DashboardIcon, link: "/dentist/dashboard" },
  {
    text: "Consent Forms",
    logo: ConsentFormIcon,
    link: "/dentist/consent-forms",
  },
  {
    text: "Procedures",
    logo: ConsentFormIcon,
    link: "/dentist/procedures",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      {/* Desktop Sidebar - now fixed */}
      <div className="hidden lg:block fixed lg:w-[19%] 2xl:w-[15%] h-screen z-30">
        <SideBar data={SIDE_BAR_DATA} />
      </div>

      {/* Mobile Sidebar Wrapper */}
      <div className="lg:hidden relative z-40">
        <SmallScreenSideBar data={SIDE_BAR_DATA} />
      </div>

      {/* Main Content - add margin to account for fixed sidebar */}
      <main className="flex-1 bg-white lg:ml-[19%] 2xl:ml-[15%] p-6 pt-0 lg:pt-6 z-0 relative">
        {children}
      </main>
    </div>
  );
}
