// import type { Metadata } from "next";
// import { ConsentFormIcon, DashboardIcon } from "@/asssets";
// import SideBarWrapper from "@/components/SideBarWrapper";
// import SmallScreenSideBarWrapper from "@/components/SmallScreenSideBarWrapper";
// import { SIDE_BAR_DATA } from "@/constants/SideBarData";

// export const metadata: Metadata = {
//   title: "Aspire Consent",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div className="flex flex-col lg:flex-row min-h-screen">
//       {/* Desktop Sidebar - now fixed */}
//       <div className="hidden lg:block fixed lg:w-[20%] 2xl:w-[15%] min-h-screen z-30">
//         <SideBarWrapper data={SIDE_BAR_DATA} />
//       </div>

//       {/* Mobile Sidebar Wrapper */}
//       <div className="lg:hidden relative z-40">
//         <SmallScreenSideBarWrapper data={SIDE_BAR_DATA} />
//       </div>

//       {/* Main Content - add margin to account for fixed sidebar */}
//       <main className="flex-1 bg-white lg:ml-[19%] 2xl:ml-[15%] p-6 pt-0 lg:pt-6 z-0 relative">
//         {children}
//       </main>
//     </div>
//   );
// }

import type { Metadata } from "next";
import { SIDE_BAR_DATA } from "@/constants/SideBarData";
import SideBarWrapper from "@/components/SideBarWrapper";

export const metadata: Metadata = {
  title: "Aspire Consent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      {/* Desktop Sidebar - always visible on lg and up */}
      <div className="hidden lg:block lg:w-64 2xl:w-72 fixed min-h-screen z-30 ">
        <SideBarWrapper data={SIDE_BAR_DATA} />
      </div>

      {/* Mobile Sidebar - handled by Header component */}

      {/* Main Content */}
      <div className="flex-1 bg-white lg:ml-64 2xl:ml-72 p-6 pt-0 lg:pt-6">
        {children}
      </div>
    </div>
  );
}
