export { default as AspireConsentWhiteLogo } from "./aspire-consent-white-logo.svg";
export { default as AspireConsentBlackLogo } from "./aspire-consent-black-logo.svg";
export { default as DashboardIcon } from "./dashboard-icon.svg";
export { default as ConsentFormIcon } from "./consent-form-icon.svg";
export { default as PatientIcon } from "./patients-icon.svg";
export { default as SettingIcon } from "./settings-icon.svg";
export { default as LogoutIcon } from "./logout-cion.svg";
export { default as ProfilePic } from "./profile-pic.svg";
export { default as LeftArrow } from "./left-arrow.png";
